In [2]:
import numpy as np

How to make arrays

In [ ]:
a = np.array([1,2,3])
print(a)

[1 2 3]


Complex Arrays:

In [ ]:
b = np.array([[3.4,3.5,2.1],[6.0,7.0,7.8]])
print(b)

[[3.4 3.5 2.1]
 [6.  7.  7.8]]


Get dimension of array

In [ ]:
a.ndim # 1 dimension array
b.ndim # 2 dimension array

2

Get Shape of array

In [ ]:
a.shape # 3 columns
b.shape # 2 rows and 3 columns

(2, 3)

How to check type of anything

In [ ]:
a.dtype

dtype('int64')

To check size , we have couple of different commands

In [ ]:
a.size # number of elements in array
a.itemsize # check the size of item
b.nbytes # check the total size

48


   
#  **Accessing / Changing Specific Elements , Rows, Colums etc**



In [24]:
x = np.array([[1,2,3,4,5,6,7,8,9],[9,8,7,6,5,4,3,2,1]])
print(x)

[[1 2 3 4 5 6 7 8 9]
 [9 8 7 6 5 4 3 2 1]]


Get specific element [ a , b ]

In [ ]:
x[1,3] # first row and 3 column

6

Get specific row

In [ ]:
x[0,:] # first full row
x[0,:3] # first row elements from (first to third)
x[0,3:] # first row elements from (third to last)
x[0,3:6] # first row elements from (third to fifth)

array([], shape=(0, 9), dtype=int64)

A little bit more fanct

In [ ]:
x[0,2:6:2] # [startindex : endindex : increment]

array([3, 5])

To change a row or column element

In [ ]:
x[1,4] = 123
print(x)

[[  1   2   3   4   5   6   7   8   9]
 [  9   8   7   6 123   4   3   2   1]]


# **Initializing Different Types of Arrays**

In [31]:
# All 0s Matrix
np.zeros(4)

# Making two dimensional or more
np.zeros((2,3,3))

# All ones matrix
np.ones(2,dtype='int32') #[1,1]
np.ones(5,dtype="int64") #[1,1,1,1,1]
np.ones((2,3),dtype="int32") #[[1,1,1],[1,1,1]]

# Now fill matrix with any number you want
np.full(2,99) #[99,99]
np.full((2,3),99) #[[99,99,99],[99,99,99]]
np.full((2,3),55,dtype="int64") #[[55,55,55],[55,55,55]]
np.full((2,3),55,dtype="float32") #[[55. 55. 55.],[55. 55. 55.]]

# Any full_like number
np.full_like(x,4) #[[4,4,4,4,4,4,4,4,4],[4,4,4,4,4,4,4,4,4]]

array([[4, 4, 4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4, 4, 4]])

In [45]:
# Generate Random Numbers
np.random.rand(2)
np.random.rand(2,3)
np.random.rand(2,5)*10

# Generate Random Int Numbers
np.random.randint(4)
np.random.randint(3,5,size=(3,3))

array([[3, 3, 4],
       [4, 3, 4],
       [3, 3, 3]])

In [47]:
# Identity Matrix
np.identity(3,dtype="int64")

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [54]:
# Repeat an Array
arr = np.array([[1,2,3]])
r = np.repeat(arr,3,axis=1)
print(r) # [[1 1 1 2 2 2 3 3 3]]


arr = np.array([[1,2,3]])
r = np.repeat(arr,3,axis=0)
print(r)
# [[1 2 3]
#  [1 2 3]
#  [1 2 3]]


[[1 1 1 2 2 2 3 3 3]]
[[1 2 3]
 [1 2 3]
 [1 2 3]]


# ***Mathematics in numpy***

In [70]:
arr = np.array([1,2,3])

arr + 2 # [3, 4, 5]
arr - 2 # [-1,  0,  1]
arr * 2 # [ 2,  4,  6]
arr / 2 # [0.5, 1. , 1.5]
arr ** 2 # [ 1,  4,  9]

# Similarly , we can use sim,cos,tan.
np.sin(arr)
np.cos(arr)
np.tan(arr)


3

In [79]:
# Find the determinant of matrix
# arr = np.identity(3)
# print(arr)
# np.linalg.det(arr)

# Inverse
arr = np.array([[1,2],[3,4]])
np.linalg.det(arr) # determinant of matrix
np.linalg.inv(arr)  # Inverse of matrix

# You can also find more in numpy documentation.

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

## **Statistics**

In [84]:
arr = np.array([[1,2,3],[4,5,6]])
np.sqrt(arr)
np.log(arr)
arr.min()
arr.sum()
arr.max()
# You can also use
np.max(arr,axis=1)

6

## **Reorganizing Arrays**

In [92]:
# 1. Reshaping arrays
before = np.array([[1,2,3,4],[5,6,7,8]])
print(before)

# Below you can reshape your matrix by changing number of rows and columns you need
after = before.reshape((8,1))
print(after)


# 2. Make stacking of arrays vertically
v1 = np.array([1,2,3])
v2 = np.array([4,5,6])
arr = np.vstack([v1,v2])
# also
arr = np.vstack([v1,v2,v1,v2])
print(arr)



# 3. Making stacking of arrays horizontally
v1 = np.array([1,2,3])
v2 = np.array([4,5,6])

arr = np.hstack([v1,v2,v2,v2])
print(arr)

[[1 2 3 4]
 [5 6 7 8]]
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]]
[[1 2 3]
 [4 5 6]
 [1 2 3]
 [4 5 6]]
[1 2 3 4 5 6 4 5 6 4 5 6]


## **Miscellaneous**

In [113]:
from google.colab import files

# Upload the file
uploaded = files.upload()

Saving data2.txt to data2 (1).txt


In [110]:
!ls

data2.txt  sample_data


In [114]:
# If you want to read data form file
data = np.genfromtxt('data2.txt',delimiter=',')

<ipython-input-114-ab6072d93be7>:2: UserWarning: genfromtxt: Empty input file: "data2.txt"
  data = np.genfromtxt('data2.txt',delimiter=',')
